Item tempItem;
tempItem = new Item("Archgriffin Mutagen","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Arenaria","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Balisse Fruit","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Basilisk Decoction","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Basilisk Hide","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Basilisk Mutagen","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Basilisk Venom","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Bear Fat","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Bear Pheromones","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Beast Oil","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Beggartick Blossoms","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Berbercane Fruit","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Berserker Hide","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Bison Grass","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Black Blood","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Blizzard","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Bloodmoss","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Blowball","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Blowbill","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Bryonia","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Buckthorn","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Calcium Equum","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Cat","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Cave Troll Liver","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Celandine","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Cherry Cordial","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Chitin Scale","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Chort Decoction","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Chort Hide","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Chort Mutagen","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Cockatrice Decoction","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Cockatrice Egg","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Cockatrice Mutagen","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Cockatrice Stomach","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Cortinarius","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Crow's Eye","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Crystallized Essence","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Cursed Oil","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Cyclops' Eye","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Dark Essence","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Devourer's Blood","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Dog Tallow","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Doppler Decoction","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Doppler Mutagen","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Draconid Oil","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Drowner Brain","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Drowner Pheromones","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Drowner Tongue","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Ducal Water","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Dwarven Spirit","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Earth Elemental Decoction","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Earth Elemental Mutagen","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Ekhidna Decoction","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Ekimmara Decoction","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Ekimmara Hide","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Ekimmara Mutagen","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Ekkidna Mutagen","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Elementa Oil","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Elemental Essence","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Empty Bottle","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Endrega Embryo","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Endrega Heart","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Enhanced Beast Oil","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Enhanced Black Blood","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Enhanced Blizzard","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Enhanced Cat","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Enhanced Cursed Oil","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Enhanced Draconid Oil","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Enhanced Elementa Oil","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Enhanced Full Moon","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Enhanced Golden Oriole","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Enhanced Hanged Man's Venom","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Enhanced Hybrid Oil","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Enhanced Insectoid Oil","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Enhanced Maribor Forest","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Enhanced Necrophage Oil","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Enhanced Ogroid Oil","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Enhanced Petri's Philter","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Enhanced Relict Oil","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Enhanced Specter Oil","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Enhanced Swallow","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Enhanced Tawny Owl","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Enhanced Thunderbolt","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Enhanced Vampire Oil","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Enhanced White Honey","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Enhanced White Rafford's Decoction","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Ergot Seeds","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Erynia Eye","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Essence of Wraith","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Fiend Decoction","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Fiend Mutagen","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Fiend's Eye","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Fifth Essence","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Foglet Decoction","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Foglet Mutagen","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Foglet Teeth","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Fool's Parsley Leaves","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Forktail Decoction","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Forktail Hide","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Forktail Mutagen","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Full Moon","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Gargoyle Dust","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Gargoyle Heart","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Ghoul's Blood","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Ginatia Petals","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Golden Oriole","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Golem's Heart","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Grave Hag Decoction","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Grave Hag Mutagen","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Grave Hag's Ear","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Greater Blue Mutagen","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Greater Green Mutagen","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Greater Red Mutagen","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Green Mold","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Griffin Decoction","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Griffin Feathers","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Griffin Mutagen","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Griffin's Egg","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Hag Tooth","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Han Fiber","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Hanged Man's Venom","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Harpy Eggs","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Harpy Feathers","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Harpy Talons","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Hellebore Petals","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Homemade Pepper Vodka","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Honeysuckle","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Hop Umbels","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Hornwort","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Hybrid Oil","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Hydragenum","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Insectoid Oil","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Katakan Decoction","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Katakan Mutagen","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Killer Whale","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Leshen Decoction","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Leshen Mutagen","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Leshen Resin","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Lesser Blue Mutagen","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Lesser Green Mutagen","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Lesser Red Mutagen","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Light Essence","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Lock of Lamia Hair","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Longrube","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Lunar Shards","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Mahakaman Spirit","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Mandrake Cordial","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Mandrake Root","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Maribor Forest","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Mistletoe","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Moleyarrow","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Monster Blood","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Monster Claw","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Monster Dust","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Monster Egg","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Monster Essence","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Monster Feather","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Monster Hair","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Monster Heart","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Monster Hide","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Monster Liver","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Monster Plate","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Monster Saliva","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Monster Tongue","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Monster Tooth","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Necrophage Hide","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Necrophage Oil","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Nekker Blood","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Nekker Claw","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Nekker Eye","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Nekker Heart","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Nekker Pheromones","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Nekker Warrior Decoction","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Nekker Warrior Mutagen","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Nekker Warrior's Liver","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Nightwraith Decoction","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Nightwraith Hair","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Nightwraith Mutagen","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Nigredo","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Nilfgaardian Lemon","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Noonwraith Decoction","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Noonwraith Mutagen","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Nostrix","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Ogroid Oil","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Oil","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Optima Mater","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Petri's Philter","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Phosphorus","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Pigskin Puffball","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Pop's Mold Antidote","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Potion of Clearance","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Pringrape","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Puffball","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Quebrith","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Quicksilver Solution","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Ranogrin","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Rebis","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Redanian Herbal","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Relict Oil","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Reliever's Decoction","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Resin","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Ribleaf","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Rotfiend Blood","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Rubedo","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Saltpeter","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Sewant Mushrooms","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Specter Dust","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Specter Oil","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Stammelford's Dust","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Succubus Decoction","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Succubus Mutagen","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Sulfur","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Superior Beast Oil","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Superior Black Blood","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Superior Blizzard","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Superior Cat","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Superior Cursed Oil","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Superior Draconid Oil","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Superior Elementa Oil","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Superior Full Moon","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Superior Golden Oriole","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Superior Hanged Man's Venom","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Superior Hybrid Oil","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Superior Insectoid Oil","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Superior Maribor Forest","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Superior Necrophage Oil","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Superior Ogroid Oil","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Superior Petri's Philter","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Superior Relict Oil","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Superior Specter Oil","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Superior Swallow","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Superior Tawny Owl","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Superior Thunderbolt","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Superior Vampire Oil","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Superior White Honey","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Superior White Rafford's Decoction","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Swallow","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Tawny Oil","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Tawny Owl","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Temerian Rye","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Thunderbolt","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Troll Claw","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Troll Decoction","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Troll Hide","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Vampire Fang","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Vampire Oil","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Vampire Saliva","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Venom Extract","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Verbena","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Vermilion","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Vitriol","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Water Essence","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Water Hag Decoction","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Water Hag Mutagen","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Water Hag Tooth","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Werewolf Decoction","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Werewolf Hide","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Werewolf Mutagen","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Werewolf Saliva","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("White Gull","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("White Honey","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("White Myrtle Petals","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("White Raffard's Decoction","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Wine Stone","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Wolf's Liver","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Wolfsbane","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Wraith Decoction","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Wraith Mutagen","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Wyvern Decoction","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Wyvern Egg","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Wyvern Hide","Description goes here","type goes here");
allItems.add(tempItem);
tempItem = new Item("Wyvern Mutagen","Description goes here","type goes here");
allItems.add(tempItem);
